---
  - name:       Install vagarant to make VMs and experiment
    dnf:
      name:     "{{ item }}"
      state:    present
    with_items:
      - libvirt
      - vagrant
      - vagrant-libvirt
      - vagrant-sshfs
    notify:
      - Reload systemd daemon
      - Start and enable libvirtd
