---
- name: Install multimedia software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - vlc
    - deluge
    - inkscape
    - shotwell
    - polari
    - foliate
  tags:
    - mutimedia

- name: Install multimedia software from flathub
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
      - com.skype.Client
      - org.signal.Signal
      - org.gnome.Podcasts
      - com.spotify.Client
      - com.github.micahflee.torbrowser-launcher
    tags:
      - mutimedia
