---
  - name:          Install multimedia, chat softwares
    dnf:
      name:        "{{ item }}"
      state:       present
    with_items:
      - gimp
      - vlc
      - youtube-dl
      - deluge
      - inkscape
      - hexchat
      - picard
      - entangle
      - shotwell
    tags:
      - mutimedia

  - name:          Make folder for softwares
    file:
      path:      "/home/{{user}}/Desktop/softwares/"
      state:     directory
    become:      false
    become_user: "{{ user }}"
    tags:
      - torbrowser


  - name:          Unarchive torbrowser to ~/Desktop/softwares
    unarchive:
      src:         "{{torbrowser_url}}"
      dest:        "/home/{{user}}/Desktop/softwares/"
      remote_src:  yes
    become:        false
    become_user:   "{{ user }}"
    tags:
        - torbrowser


  - name:          Make desktop entry for torbrowser
    template:
      src:       torbrowser.j2
      dest:      ~/.local/share/applications/torbrowser.desktop
    become:      false
    become_user: "{{ user }}"
    tags:
      - torbrowser
      - torbrowser_icon


  - name:         Install Skype
    become:       yes
    command:      flatpak install --assumeyes flathub com.skype.Client

  - name:         Install Signal
    become:       yes
    command:      flatpak install --assumeyes flathub org.signal.Signal

  - name:         Install Web Torrent
    become:       yes
    command:      flatpak install --assumeyes flathub io.webtorrent.WebTorrent
