---
- name: Install multimedia, chat softwares
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - gimp
    - vlc
    - youtube-dl
    - deluge
    - inkscape
    - picard
    - shotwell
  tags:
    - mutimedia

- name: Install Skype
  command: flatpak install --assumeyes flathub com.skype.Client

- name: Install Signal
  command: flatpak install --assumeyes flathub org.signal.Signal

- name: Install Riot
  command: flatpak install --assumeyes flathub im.riot.Riot

- name: Install Podcasts
  command: flatpak install --assumeyes flathub org.gnome.Podcasts

- name: Install Tor Launcher
  command: flatpak install --assumeyes flathub com.github.micahflee.torbrowser-launcher
