---
- name: Update packages and install basic packages
  hosts: all
  become: true
  roles:
    - basic
  tags:
    - basic

- name: Setup and install development tools, libraries and dependencies
  hosts: all
  become: true
  roles:
    - development
  tags:
    - development

- name: Install necessary utils and packages
  hosts: all
  become: true
  roles:
    - utils
  tags:
    - utils

- name: Install all necessary multimedia softwares
  hosts: all
  become: true
  roles:
    - multimedia
  tags:
    - multimedia

- name: Install more wallpapers
  hosts: all
  become: true
  roles:
    - wallpapers
  tags:
    - wallpapers

- name: Install virtualization softwares
  hosts: all
  become: true
  roles:
    - virtualization
  tags:
    - virtualization

- name: Configure vim and fish
  hosts: all
  become: true
  roles:
    - configure
  tags:
    - configure
