---
  - name:         Install vim, fish, tilix
    dnf:
      name:       "{{ item }}"
      state:      present
    with_items:
      - vim
      - fish
      - tilix
    tags:
      - terminal


  - name:         Install global npm packages.
    npm:
      name:       "{{ item }}"
      global:     yes
      state:      present
    with_items:
      - mocha
      - forever
      - grunt
      - gulp
      - bower
      - newman
      - '@vue/cli'
      - vue-language-server
      - n
    tags:
      - npm


  - name:         Install pip packages.
    pip:
      name:       "{{ item }}"
      executable: pip3
      state:      present
    with_items:
      - httpie
      - isort
      - mypy
      - flake8
      - coala-bears
      - cookiecutter
      - Sphinx
      - pipenv
      - python-language-server
      - black
    tags:
      - pip


  - name:         Add GPG key for atom
    rpm_key:
      state:      present
      key:        "{{atom_gpgkey_url}}"
    tags:
      - atom


  - name:         Copy atom.repo to yum.repos.d
    copy:
      src:        atom.repo
      dest:       /etc/yum.repos.d/atom.repo
      owner:      root
      group:      root
      mode:       0644
    tags:
      - atom


  - name:         Install atom text editor
    dnf:
      name:       atom
      state:      present
    tags:
      - atom


  - name:         Make folder for softwares
    file:
      path:       "/home/{{user}}/Desktop/softwares/"
      state:      directory
    become:       false
    become_user:  "{{ user }}"
    tags:
      - postman


  - name:         Unarchive postman to ~/Desktop/softwares
    unarchive:
      src:        "{{postman_url}}"
      dest:       "/home/{{user}}/Desktop/softwares/"
      remote_src: yes
    become:       false
    become_user:  "{{ user }}"
    tags:
      - postman


  - name: Make desktop entry for Postman
    template:
      src: postman.j2
      dest: ~/.local/share/applications/postman.desktop
    become:       false
    become_user:  "{{ user }}"
    tags:
      - postman
      - postman_icon
