---
  - name:            Reload systemd daemon
    systemd:
      state:         restarted
      daemon_reload: yes
      name:          crond

  - name:            Start and enable powertop
    systemd:
      name:          powertop
      state:         started
      enabled:       True
