---
- name: Install utils
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mediawriter
    - nuntius
    - labyrinth
    - powertop
    - gnome-todo
    - wireshark
    - ibus-typing-booster
    - hunspell-en
    - hunspell-hi
    - chromium
    - onionshare
    - gnome-shell-extension-pomodoro
    - exa
    - ripgrep
    - putty
  notify:
    - Reload systemd daemon
    - Start and enable powertop

- name: Added user to wireshark group
  user:
    name: "{{ user }}"
    groups: wireshark
    append: yes

- name: Install Dropbox
  command: flatpak install --assumeyes flathub com.dropbox.Client

- name: Install GeoGebra
  command: flatpak install --assumeyes flathub org.geogebra.GeoGebra

- name: Install App Editor
  command: flatpak install --assumeyes flathub com.github.donadigo.appeditor

- name: Install KeePassXC password manager
  command: flatpak install --assumeyes flathub org.keepassxc.KeePassXC
