---
- name: Install utils
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mediawriter
    - ibus-typing-booster
    - hunspell-en
    - hunspell-hi
    - onionshare
    - lsd
    - ripgrep
    - bat
    - fd-find
    - tldr
    - ytop
    - starship
  tags:
    - utils

- name: Install Developer Tools from flathub
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
      - com.dropbox.Client
      - com.github.donadigo.appeditor
      - com.bitwarden.desktop
    tags:
      - utils
