---
- name: Install utils
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mediawriter
    - nuntius
    - labyrinth
    - powertop
    - ibus-typing-booster
    - hunspell-en
    - hunspell-hi
    - onionshare
    - gnome-shell-extension-pomodoro
    - exa
    - ripgrep
  notify:
    - Reload systemd daemon
    - Start and enable powertop

- name: Install Dropbox
  command: flatpak install --assumeyes flathub com.dropbox.Client

- name: Install GeoGebra
  command: flatpak install --assumeyes flathub org.geogebra.GeoGebra

- name: Install App Editor
  command: flatpak install --assumeyes flathub com.github.donadigo.appeditor