---
- name: Update all dnf packages
  dnf:
    name: "*"
    state: latest
  tags:
    - update

- name: Get version of Fedora
  command: rpm -E %fedora
  register: fedora_version
  tags:
    - rpmfusion

- name: Install rpmfusion repositories
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{rpmfusion_free_release}}"
    - "{{rpmfusion_nonfree_release}}"
  tags:
    - rpmfusion

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak
