---
- name: Install Development Libraries
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib.i686
    - ncurses-libs.i686
    - bzip2-libs.i686
    - glibc.i686
    - glibc-devel.i686
    - libstdc++.i686
    - zlib-devel.i686
    - ncurses-devel.i686
    - libX11-devel.i686
    - libXrender.i686
    - libXrandr.i686
    - "@Development Tools"
    - "@C Development Tools and Libraries"
    - "@Basic Desktop"
    - dnf-plugins-core
  tags:
    - development-libraries

- name: Install Programming Languages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - rust
  tags:
    - programming-languages

- name: Install Developer Tools
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - httpie
    - pipenv
    - python3-black
    - python3-isort
    - python3-flake8
    - python3-mypy
    - python3-cookiecutter
    - pre-commit
    - cargo
    - fish
    - vim
    - tilix
    tags:
      - developer-tools


- name: Install Developer Tools from flathub
  flatpak:
    name: "{{ item }}"
    state: present
  with_items:
      - com.visualstudio.code
      - com.getpostman.Postman
    tags:
      - developer-tools
