---
- name: Install vim plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs "{{vim_plug_url}}"
  become: false
  become_user: "{{ user }}"
  tags:
    - vim

- name: Get vimrc for user
  copy:
    src: vimrc
    dest: "$HOME/.vimrc"
    owner: "{{user}}"
    group: "{{user}}"
  tags:
    - vim

- name: Set fish as default shell
  user:
    name: "{{ user }}"
    shell: /usr/bin/fish
  tags:
    - fish
