---
  - name:       Install Programming Languages and development depandancies
    dnf:
      name:     "{{ item }}"
      state:    present
    with_items:
     - java-openjdk
     - icedtea-web
     - nodejs
     - go
     - rust
     - elixir
    tags:
      - programming_lang
